name: Test

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12.4", "3.12"]
    env:
      BGC_CONFIG_DIR: /tmp/boardgamecompanion/config
      BGC_IMPORT_DIR: /tmp/boardgamecompanion/import
      BGC_MANUALS_DIR: /tmp/boardgamecompanion/manuals
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install
        run: pip install -e ".[dev]"
      - name: Test
        run: pytest -q
